version: '3'

networks:
  app:
volumes:
  project-name_database:

services:
  db:
    image: mysql:5.7
    container_name: project_db
    tty: true
    volumes:
      - "project-name_database:/var/lib/mysql"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: project_db
      MYSQL_USER: project_user
      MYSQL_PASSWORD: password
    networks:
      - app

  app:
    build:
      context: ./docker
      dockerfile: App.DockerFile
    container_name: project_app
    ports:
      - "8080:80"
    volumes:
      - "./:/var/www/html"
      - "./docker/site.conf:/etc/apache2/sites-enabled/000-default.conf"
    depends_on:
      - db
    networks:
      - app

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: project_phpmyadmin
    ports:
      - "8081:80"
    environment:
      - PMA_ARBRITARY=1
      - PMA_HOST=db
    depends_on:
      - db
    networks:
      - app
